services:
  - type: web
    name: kitchen-backend
    env: node
    rootDir: backend
    buildCommand: npm install && npx prisma generate && npx prisma migrate deploy
    startCommand: npm run start
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: kitchen-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: ALLOW_ADMIN_REGISTER
        value: "true"
      - key: CORS_ORIGIN
        value: "https://imperii.kz"

databases:
  - name: kitchen-db
    plan: free
    databaseName: kitchen
    user: kitchen
